FROM node:20.11.1-alpine

ARG API_SERVER
ARG NEXT_PUBLIC_API_SERVER
ARG SERVER_TOKEN
ARG NEXT_PUBLIC_SERVER_TOKEN

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ENV API_SERVER=$API_SERVER
ENV NEXT_PUBLIC_API_SERVER=$NEXT_PUBLIC_API_SERVER
ENV SERVER_TOKEN=$SERVER_TOKEN
ENV NEXT_PUBLIC_SERVER_TOKEN=$NEXT_PUBLIC_SERVER_TOKEN

RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]