name: naserpapidev

services:
  app:
    image: ghcr.io/${GHCR_OWNER}/naserpapidev:${IMAGE_TAG:-latest}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
    expose:
      - "3000"
    healthcheck:
      test: [ "CMD-SHELL", "wget -qO- http://localhost:3000 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

  caddy:
    image: caddy:2
    restart: unless-stopped
    depends_on:
      app:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    environment:
      EMAIL: ${EMAIL}
      DOMAIN: ${DOMAIN}

volumes:
  caddy_data:
  caddy_config:
