FROM node:20.11.1-alpine
ARG DATABASE_URL
ARG API_SERVER
ARG NEXT_PUBLIC_API_SERVER


WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .
ENV DATABASE_URL=$DATABASE_URL
ENV API_SERVER=$API_SERVER
ENV NEXT_PUBLIC_API_SERVER=$NEXT_PUBLIC_API_SERVER
RUN npm run build

EXPOSE 3000

CMD ["npm", "run", "start"]
